version: '3.8'
services:
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:5.5.3
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   networks:
  #     - app-network
  # kafka:
  #   image: confluentinc/cp-enterprise-kafka:5.5.3
  #   depends_on: [zookeeper]
  #   ports:
  #     - 9092:9092
  #   environment:
  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092,EXTERNAL_DIFFERENT_HOST://38.25.18.1:29093
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,EXTERNAL_DIFFERENT_HOST:PLAINTEXT
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_JMX_PORT: 9991
  #   networks:
  #     - app-network
  message-manager:
    image: "message_manager"
    container_name: "message_manager"
    # env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
    networks:
      - app-network
networks:
  app-network:
      driver: bridge
volumes:
  message-manager-volume:
    driver: local

